export const FETCHTOPRATEDMOVIES = 'TMDB/TOPRATEDMOVIES';
export const SELECTEDMOVIE = 'TMDB/SELECTEDMOVIE';
export const SELECTEDMOVIECREDITS = 'TMDB/SELECTEDMOVIECREDITS';
export const FINDCONTENT = 'TMDB/FINDALLCONTENT';
export const CHANGECONTENT = 'TMDB/CHANGECONTENT';
export const CHANGECATEGORY = 'TMDB/CHANGECATEGORY';

